<?php
//WEB/admin-home.php
define("TITRE_ADMIN","Administrator");
define("MENU_NAVIGATION","Navigation menu");

define("DROP_MENU_LANG", "Language");
define("DROP_MENU_FR", "French");
define("DROP_MENU_EN", "English");

define("DECONNEXION", "log-out");
define("BIENVENUE","Welcome");

define("GES_USERS","Users management");
define("GES_SUBS","Subscriptions management");
define("GES_SERVICES","Services management");
define("CONSULT_HISTORY_BOOKINGS","Consult bookings history");

//WEB/ges-users/ges-users.php
define("DISPLAY_USERS", "Display all users");
define("ADD_USER", "Add an user");

define("SEARCH_BAR_CLIENT", "Search a customer");
define("SEARCH_BAR", "Search");
define("HELP_SEARCH_BAR", "Search bar assistance");
define("HOW_TO_SEARCH_BAR", "How to use the search bar?");
define("HOW_TO_SEARCH_BAR_CONDITION", "You should search for one of the following:");
define("HOW_TO_SEARCH_BAR_NAME", "-a name");
define("HOW_TO_SEARCH_BAR_FIRST_NAME", "-a firstname");
define("HOW_TO_SEARCH_BAR_EMAIL", "-an email");
define("HOW_TO_SEARCH_BAR_PSEUDO", "-a pseudo");
define("HOW_TO_SEARCH_BAR_PHONE", "-a phone number");
define("HOW_TO_SEARCH_BAR_REMARK", "You can search for word initials but the search will be less precise");
define("SEARCH_BAR_CLOSE", "close");

define("USER_ID", "ID");
define("USER_NAME", "Name");
define("USER_FIRST_NAME", "Firstname");
define("USER_PSEUDO", "Pseudo");
define("USER_EMAIL", "Email");
define("USER_BIRTHDAY", "Birthday");
define("USER_GENDER", "Gender");
define("USER_PHONE", "Phone number");
define("USER_ADDRESS", "Address");
define("USER_STATUS", "Status");
define("USER_SUBSCRIBED_TO", "Subscribed to");
define("USER_DISABLE_ACCOUNT", "Disable account");
define("USER_MUST_CONFIRM_EMAIL", "Must confirm his email");
define("USER_ACTIVATE_ACCOUNT", "Activate account");
define("USER_UPDATE", "Update");
define("USER_DROP", "Drop for good");
define("USER_PASSWORD", "Password");
define("USER_CONFIRM_PASSWORD", "Password's confirmation");

define("ADDRESS_NUMBER_STREET", "N° street");
define("ADDRESS_1", "Addresse n°1");
define("ADDRESS_POST_CODE_1", "Postcode n°1");
define("ADDRESS_2", "Addresse n°2 (optionnal)");
define("ADDRESS_POST_CODE_2", "Postcode n°2 (optionnal)");
define("CITY", "City");
define("BIRTHDAY_IN_A_DATE_FORMAT", "mm/dd/yyyy");
define("MOBILE", "Mobile");

define("MAN", "Man");
define("WOMAN", "Woman");
define("OTHER", "Other");

//WEB/ges-subscription/ges-users
define("TITRE_SUBSCRIPTION_OFFER","Subscriptions offer management");
define("ADD_SUBSCRIPTION_OFFER", "Add subscription offer");
define("ADD_OFFER", "Add offer");
define("DISPLAY_SUBSCRIPTIONS_OFFER", "Display the subscriptions offer");

define("SUBSCRIPTION_OFFER_ID", "ID");
define("SUBSCRIPTION_OFFER_NAME", "Susbcription's name");
define("SUBSCRIPTION_OFFER_PRICE", "Price");
define("SUBSCRIPTION_OFFER_HOUR_PER_MONTH", "Hour per month");
define("SUBSCRIPTION_OFFER_OPEN_TIME", "Open Time");
define("SUBSCRIPTION_OFFER_STATUS", "Status");
define("SUBSCRIPTION_OFFER_DISABLED", "Disable offer");
define("SUBSCRIPTION_OFFER_ACTIVATED", "Enable offer");
define("SUBSCRIPTION_OFFER_UPDATED", "Update offer");
define("SUBSCRIPTION_OFFER_DROP", "Delete offer");

?>
