<?php
//WEB/admin-home.php
define("TITRE_ADMIN","Administrateur");
define("MENU_NAVIGATION","Menu de navigation");

define("DROP_MENU_LANG", "Langage");
define("DROP_MENU_FR", "Français");
define("DROP_MENU_EN", "Anglais");

define("DECONNEXION", "Se déconnecter");
define("BIENVENUE","Bienvenue");

define("GES_USERS","Gestion des utilisateurs");
define("GES_SUBS","Gestion des abonnements");
define("GES_SERVICES","Gestion des services");
define("CONSULT_HISTORY_BOOKINGS","Consulter l'historique des réservations");

//WEB/ges-users/ges-users.php
define("DISPLAY_USERS", "Afficher tous les utilisateurs");
define("ADD_USER", "Ajouter un utilisateur");

define("SEARCH_BAR_CLIENT", "Rechercher un client");
define("SEARCH_BAR", "Chercher");
define("HELP_SEARCH_BAR", "Aide sur la barre de recherche");
define("HOW_TO_SEARCH_BAR", "Comment utiliser la barre de recherche?");
define("HOW_TO_SEARCH_BAR_CONDITION", "Vous devez rechercher un des éléments suivants:");
define("HOW_TO_SEARCH_BAR_NAME", "-un nom");
define("HOW_TO_SEARCH_BAR_FIRST_NAME", "-un prénom");
define("HOW_TO_SEARCH_BAR_EMAIL", "-un email");
define("HOW_TO_SEARCH_BAR_PSEUDO", "-un pseudo");
define("HOW_TO_SEARCH_BAR_PHONE", "-un numéro de téléphone");
define("HOW_TO_SEARCH_BAR_REMARK", "Vous pouvez rechercher des initiales de mots mais la recherche sera moins précise");
define("SEARCH_BAR_CLOSE", "fermer");

define("USER_ID", "ID");
define("USER_NAME", "Nom");
define("USER_FIRST_NAME", "Prénom");
define("USER_PSEUDO", "Pseudo");
define("USER_EMAIL", "Email");
define("USER_BIRTHDAY", "Date de naissance");
define("USER_GENDER", "Civilité");
define("USER_PHONE", "N° Téléphone");
define("USER_ADDRESS", "Adresse postale");
define("USER_STATUS", "Status");
define("USER_SUBSCRIBED_TO", "Abonné(e) à");
define("USER_DISABLE_ACCOUNT", "Désactiver compte");
define("USER_MUST_CONFIRM_EMAIL", "Doit confirmer son mail");
define("USER_ACTIVATE_ACCOUNT", "Activer compte");
define("USER_UPDATE", "Mettre à jour");
define("USER_DROP", "Supprimer définitivement");
define("USER_PASSWORD", "Mot de passe");
define("USER_CONFIRM_PASSWORD", "Confirmation du mot de passe");

define("ADDRESS_NUMBER_STREET", "N° voie");
define("ADDRESS_1", "Adresse n°1");
define("ADDRESS_POST_CODE_1", "Code postal n°1");
define("ADDRESS_2", "Adresse n°2 (facultatif)");
define("ADDRESS_POST_CODE_2", "Code postal n°2 (facultatif)");
define("CITY", "Ville");
define("BIRTHDAY_IN_A_DATE_FORMAT", "jj/mm/aaaa");
define("MOBILE", "Mobile");

define("MAN", "Homme");
define("WOMAN", "Femme");
define("OTHER", "Autre");
?>
